travis:
  secure:
    BINSTAR_TOKEN: T1O7LZaek+A4CaUF2v+nnhCzOE9cVavlcqduu8ZvNuHUsCaH90abCMJinu5eFEZCimCydZly3sLQ4yGd1mzMCA8/ipH9HcKL8CSwCEMXByUKrsR27zgT2TMrUNkQ8/tX5Qb6jTPzlQZAg/B0KqAsJ/DaOSkM1g+weIAa7R4q9HSNNMWFGNaA7x/pQW04vPzj/38O4WFaTpOnQq30AIELaZevsKVYwfZcR2Kg/+Fae4Ze1EEVby8dh77lKZrnZJsR32W722Tmn98Cw8g9C7P6uzyEcsJ2T3VuEA0c72zHmfM7WdoyI4THUnCtNTCDQYgiJSU2q+IV3vxpwV8Pj16RrNchryN6N2x5V+sMw+RQ1FvHJ59LnmUnwmYSK+HjnzWfIsxigHGOOLwKkm1whoIwAls2GxbT5SNXMrc6VgSMSDVGDbUWK96W6z9zQW5ze+tHyE5dq+QpX5ABnd4HDyqgtID1AZ3t9EuvLcWmYAb2NqpQVO+pnGueiIgrdHX7VW1qJuqcf5HL7ZUV8IU+TV2Tm/1nT8r2YdbtAPSI+G2e/Q35klwnxEYnRl5g1lGiWho2EL8WJJ4SBhdcS+TOUSOjlSfGBGKyhNwpo1vJIwfLwtD6UcjdtdITNIiIGR3k0jV4we3eYDOsRRBkjoUVAlf+sjnmsz/zT7yXyavYY97rCs0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
